//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.Website.RatingReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RatingReference.IRating")]
    public interface IRating {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRating/Get", ReplyAction="http://tempuri.org/IRating/GetResponse")]
        MC.ApplicationServices.DTOs.RatingDto[] Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRating/Get", ReplyAction="http://tempuri.org/IRating/GetResponse")]
        System.Threading.Tasks.Task<MC.ApplicationServices.DTOs.RatingDto[]> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRating/Post", ReplyAction="http://tempuri.org/IRating/PostResponse")]
        string Post(MC.ApplicationServices.DTOs.RatingDto ratingDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRating/Post", ReplyAction="http://tempuri.org/IRating/PostResponse")]
        System.Threading.Tasks.Task<string> PostAsync(MC.ApplicationServices.DTOs.RatingDto ratingDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRating/Delete", ReplyAction="http://tempuri.org/IRating/DeleteResponse")]
        string Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRating/Delete", ReplyAction="http://tempuri.org/IRating/DeleteResponse")]
        System.Threading.Tasks.Task<string> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRating/GetById", ReplyAction="http://tempuri.org/IRating/GetByIdResponse")]
        MC.ApplicationServices.DTOs.RatingDto GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRating/GetById", ReplyAction="http://tempuri.org/IRating/GetByIdResponse")]
        System.Threading.Tasks.Task<MC.ApplicationServices.DTOs.RatingDto> GetByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRatingChannel : MC.Website.RatingReference.IRating, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RatingClient : System.ServiceModel.ClientBase<MC.Website.RatingReference.IRating>, MC.Website.RatingReference.IRating {
        
        public RatingClient() {
        }
        
        public RatingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RatingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RatingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RatingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MC.ApplicationServices.DTOs.RatingDto[] Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<MC.ApplicationServices.DTOs.RatingDto[]> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public string Post(MC.ApplicationServices.DTOs.RatingDto ratingDto) {
            return base.Channel.Post(ratingDto);
        }
        
        public System.Threading.Tasks.Task<string> PostAsync(MC.ApplicationServices.DTOs.RatingDto ratingDto) {
            return base.Channel.PostAsync(ratingDto);
        }
        
        public string Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public MC.ApplicationServices.DTOs.RatingDto GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<MC.ApplicationServices.DTOs.RatingDto> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
    }
}
