//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.Website.GenreReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GenreReference.IGenre")]
    public interface IGenre {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenre/Get", ReplyAction="http://tempuri.org/IGenre/GetResponse")]
        MC.ApplicationServices.DTOs.GenreDto[] Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenre/Get", ReplyAction="http://tempuri.org/IGenre/GetResponse")]
        System.Threading.Tasks.Task<MC.ApplicationServices.DTOs.GenreDto[]> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenre/Post", ReplyAction="http://tempuri.org/IGenre/PostResponse")]
        string Post(MC.ApplicationServices.DTOs.GenreDto genreDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenre/Post", ReplyAction="http://tempuri.org/IGenre/PostResponse")]
        System.Threading.Tasks.Task<string> PostAsync(MC.ApplicationServices.DTOs.GenreDto genreDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenre/Delete", ReplyAction="http://tempuri.org/IGenre/DeleteResponse")]
        string Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenre/Delete", ReplyAction="http://tempuri.org/IGenre/DeleteResponse")]
        System.Threading.Tasks.Task<string> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenre/GetById", ReplyAction="http://tempuri.org/IGenre/GetByIdResponse")]
        MC.ApplicationServices.DTOs.GenreDto GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenre/GetById", ReplyAction="http://tempuri.org/IGenre/GetByIdResponse")]
        System.Threading.Tasks.Task<MC.ApplicationServices.DTOs.GenreDto> GetByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGenreChannel : MC.Website.GenreReference.IGenre, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenreClient : System.ServiceModel.ClientBase<MC.Website.GenreReference.IGenre>, MC.Website.GenreReference.IGenre {
        
        public GenreClient() {
        }
        
        public GenreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MC.ApplicationServices.DTOs.GenreDto[] Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<MC.ApplicationServices.DTOs.GenreDto[]> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public string Post(MC.ApplicationServices.DTOs.GenreDto genreDto) {
            return base.Channel.Post(genreDto);
        }
        
        public System.Threading.Tasks.Task<string> PostAsync(MC.ApplicationServices.DTOs.GenreDto genreDto) {
            return base.Channel.PostAsync(genreDto);
        }
        
        public string Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public MC.ApplicationServices.DTOs.GenreDto GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<MC.ApplicationServices.DTOs.GenreDto> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
    }
}
